services:
  server:
    image: webforum-app
    build:
      context: .
      dockerfile: ./cmd/server/Dockerfile
    ports:
      - '4000:4000'
    depends_on:
      - mysql-db
    environment:
      SERVER_PORT: 4000
  mysql-db:
    image: mysql
    ports:
      - '3306:3306'
    volumes:
      - ./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    environment:
      MYSQL_DSN: ${MYSQL_DSN}
